[settings]
lockfile = true

[tools]
actionlint = "1.7.12"
just = "1.58.0"
pinact = "4.1.1"
tombi = "1.4.1"
"github:EmbarkStudios/cargo-deny" = "0.20.2"
"github:bnjbvr/cargo-machete" = "0.9.2"
"github:nextest-rs/nextest" = "cargo-nextest-0.9.143"
"github:rust-secure-code/cargo-auditable" = "0.7.5"
