name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true

jobs:
  fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly
      - uses: taiki-e/install-action@just
      - run: just fmt-check
  machete:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@just
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-machete
      - run: just machete
  audit:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@just
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit
      - run: just audit

  test:
    runs-on: ubuntu-24.04
    needs:
      - fmt
      - machete
      - audit
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@cargo-nextest
      - run: just test
  doc:
    runs-on: ubuntu-24.04
    needs:
      - fmt
      - machete
      - audit
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@just
      - run: just doc
  clippy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2022
          - macos-15
          - ubuntu-24.04
    needs:
      - fmt
      - machete
      - audit
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - uses: taiki-e/install-action@just
      - run: just clippy

  bench:
    runs-on: ubuntu-24.04
    needs:
      - test
      - doc
      - clippy
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@cargo-nextest
      - run: just bench
