name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - Cargo.toml
      - Cargo.lock
      - "**.rs"
  push:
    branches:
      - main
      - develop
    paths:
      - Cargo.toml
      - Cargo.lock
      - "**.rs"

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly
      - uses: taiki-e/install-action@just
      - run: just fmt-check

  test:
    runs-on: ubuntu-24.04
    needs:
      - fmt
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@cargo-nextest
      - run: just test
  doc:
    runs-on: ubuntu-24.04
    needs:
      - fmt
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@just
      - run: just doc
  clippy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2022
          - macos-15
          - ubuntu-24.04
    needs:
      - fmt
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - uses: taiki-e/install-action@just
      - run: just clippy

  bench:
    runs-on: ubuntu-24.04
    needs:
      - test
      - doc
      - clippy
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@cargo-nextest
      - run: just bench
