name: Dependencies

on:
  pull_request:
    paths:
      - Cargo.toml
      - Cargo.lock
  push:
    branches:
      - main
      - develop
    paths:
      - Cargo.toml
      - Cargo.lock

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  machete:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@just
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-machete
      - run: just machete
  audit:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@just
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit
      - run: just audit
